# Generated by Django 2.2.6 on 2019-11-01 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=50)),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application_1.director')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='application_1.manager')),
            ],
        ),
    ]
